name: Generate Cypress Report
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 129
    runs-on: ubuntu-22.04
    container: cypress/browsers:node-20.18.0-chrome-129.0.6668.89-1-ff-131.0.2-edge-129.0.2792.65-1
    steps:
      - uses: actions/checkout@v4

      - name: Install Cypress and verify
        run: |
          npm ci
          npx cypress verify

      - name: Ensure reports directory exists
        run: mkdir -p cypress/reports

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: false

      - name: Ensure reports exist before merging
        run: |
          if [ -z "$(ls -A cypress/reports/*.json 2>/dev/null)" ]; then 
            echo "No reports found. Skipping merge."; 
            exit 1; 
          fi

      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report

      - name: Copy test execution video and screenshots
        run: |
          mkdir -p public
          if [ -d cypress/videos ]; then cp -r cypress/videos public/videos; fi
          if [ -d cypress/screenshots ]; then cp -r cypress/screenshots public/screenshots; fi

      - name: Deploy report page on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
