name: Generate Cypress Report
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 129
    runs-on: ubuntu-22.04
    container: cypress/browsers:node-20.18.0-chrome-129.0.6668.89-1-ff-131.0.2-edge-129.0.2792.65-1
    steps:
      - uses: actions/checkout@v4

      - name: Install Cypress and verify
        run: |
          npm ci
          npx cypress verify

      - name: Ensure reports directory exists
        run: mkdir -p public cypress/reports

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: false

      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report

      - name: Move reports to root
        run: |
          mkdir -p public
          mv cypress/reports/*.html public/index.html

      - name: Deploy report page on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports
          publish_branch: gh-pages
